name = "videograb-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "8cf7456b44767c5e0b2d58e6072f2fae"

workers_dev = true

routes = [
  { pattern = "api.vgrab.dpdns.org/*", zone_name = "vgrab.dpdns.org" }
]
